language: java
jdk:
  - oraclejdk8
env:
  global:
    - CODECOV_TOKEN=:d970f56a-a411-4caf-8e43-d9edb5aadc42
sudo: true
services:
 - docker
 - postgres
install: true
before_install:
 - docker-compose up --build -d event-store
 - bash run.sh
 - psql -c "CREATE DATABASE my_event_sourcing;" -U postgres
 - psql -c "CREATE USER es_db WITH PASSWORD 'es_db';" -U postgres
script:
 - mvn clean install -Dspring.profiles.active=ci,postgres
after_success:
 - bash <(curl -s https://codecov.io/bash)
 - docker-compose down
cache:
  directories:
  - $HOME/.m2