language: java
jdk:
  - oraclejdk8
sudo: true
services:
  - docker
before_install:
 - docker-compose up
install: true
script:
 - mvn clean install
after_success:
 - bash <(curl -s httpmvn s://codecov.io/bash)