version: '2'
services:
 setup:
    image: maven:3.5.0-jdk-8
    volumes:
      - .:/home/application
    command: ["/home/application/run.sh"]
    depends_on:
      - event-store
 event-store:
   image: eventstore/eventstore
   extra_hosts:
     - "eventstore.com:127.0.0.1"
   ports:
     - "2113:2113"
     - "1113:1113"
 postgres1:
   image: postgres:9.6
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=my_event_sourcing
     - POSTGRES_USER=es_db
     - POSTGRES_PASSWORD=es_db
     - MAX_CONNECTIONS=300